### ISSUE TITLE
Getting error adding to database after upgrade 

### ISSUE THREAD

**Issue by prsmith777** [algertc/ALPR-Database#27]
Unable to add license plate to database after upgrading.  

See attached log
[log.txt](https://github.com/user-attachments/files/18001138/log.txt)

I am seeing the camera column under live feed

**Comment by algertc** [comment]
Please update your compose file with the latest changes (In the db section: new volume & command section added) and download the migrations.sql file. This will update your database schema to include the latest changes. Right now you're still on the previous database schema.

I unfortunately don't have a good way to update the update instructions for previous versions, so the previous version doesn't explain that you need to do this. It will from now on and there shouldn't be any more changes like this. I originally misunderstood the way the database setup worked with docker which is why I had to make this change.

Apologies for the confusion

**Comment by prsmith777** [comment]
OOF  I had switched the compose file but forgot to rename it correctly.  Thanks
